import { Typography } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography variant="h1" component="h1" style={{ fontFamily: "LeagueSpartanBold" }}>HELLO IM CARLOS</Typography><img src=''></img>

        <p className={styles.description}>
          and this is my portfolio
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Link href="/About" >
              <h2>About Me &rarr;</h2>
            </Link>
            <p>Learn something more about me.</p>
          </div>
          <div className={styles.card}>
            <Link href="/Studies">
              <h2>My Studies &rarr;</h2>
            </Link>
            <p>Learn about were I studied and my Profesional Titles</p>
          </div>
          <div className={styles.card}>
            <Link href="/Experience">
              <h2>My Projects &rarr;</h2>
            </Link>
            <p>Discover the projects I worked in .</p>
          </div>
          <div
            className={styles.card}>
            <Link href="/Habilities">
            <h2>My Habilities &rarr;</h2></Link>
            <p>
              The habilities I gained with the past of the time
            </p>
           </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/Misil4/CV-Carlos-Silva"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Typography variant="h5" style={{fontWeight : "Bold"}}>Carlos Silva</Typography>
          </span>
        </a>
      </footer>
    </div>
  )
}
